# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('photo_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'agency',
                'verbose_name_plural': 'agencies',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('photo_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BadgeAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'E-Mail'), ('phone', 'Phone'), ('fax', 'Fax'), ('twitter', 'Twitter'), ('github', 'GitHub'), ('yo', 'Yo'), ('website', 'Cyber Website')], max_length=128)),
                ('label', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('note', models.CharField(blank=True, max_length=128)),
                ('preferred', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('photo_url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=128)),
                ('bio', models.TextField(blank=True)),
                ('active', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('buddy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buddies', to='mandelbrot.Expert')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('latitude', models.CharField(max_length=128)),
                ('longitude', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('tips', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('note', models.CharField(blank=True, max_length=128)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('presentable', models.BooleanField()),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_names', to='mandelbrot.Expert')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('mission', models.TextField()),
                ('description', models.TextField()),
                ('active', models.BooleanField()),
                ('agencies', models.ManyToManyField(related_name='projects', to='mandelbrot.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('part_time', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='mandelbrot.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('icon', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='projectmember',
            name='roles',
            field=models.ManyToManyField(to='mandelbrot.Role'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='mandelbrot.Expert'),
        ),
        migrations.AddField(
            model_name='project',
            name='experts',
            field=models.ManyToManyField(through='mandelbrot.ProjectMember', to='mandelbrot.Expert'),
        ),
        migrations.AddField(
            model_name='project',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='projects', to='mandelbrot.Office'),
        ),
        migrations.AddField(
            model_name='expert',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='experts', to='mandelbrot.Interest'),
        ),
        migrations.AddField(
            model_name='expert',
            name='projects',
            field=models.ManyToManyField(through='mandelbrot.ProjectMember', to='mandelbrot.Project'),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='mandelbrot.Expert'),
        ),
        migrations.AddField(
            model_name='badgeaward',
            name='awarded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges_given', to='mandelbrot.Expert'),
        ),
        migrations.AddField(
            model_name='badgeaward',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipiants', to='mandelbrot.Badge'),
        ),
        migrations.AddField(
            model_name='badgeaward',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='mandelbrot.Expert'),
        ),
    ]
