# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandelbrot', '0002_auto_20160207_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='label',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
