# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandelbrot', '0003_auto_20160209_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='phonetic_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='expert',
            name='sort_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
