# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandelbrot', '0004_auto_20160211_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetail',
            name='official',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
