# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandelbrot', '0008_auto_20151122_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='type',
            field=models.CharField(choices=[('email', 'E-Mail'), ('phone', 'Phone'), ('fax', 'Fax'), ('twitter', 'Twitter'), ('yo', 'Yo')], max_length=128),
        ),
        migrations.AddField(
            model_name='expert',
            name='interests',
            field=models.ManyToManyField(related_name='experts', to='mandelbrot.Interest'),
        ),
    ]
