# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandelbrot', '0009_auto_20160130_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='tips',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
