# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandelbrot', '0013_auto_20160130_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetail',
            name='preferred',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='public',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
