# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandelbrot', '0014_auto_20160130_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='email',
        ),
    ]
