# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandelbrot', '0018_agency_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='experts', to='mandelbrot.Interest'),
        ),
    ]
