# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandelbrot', '0019_auto_20160131_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='title',
            new_name='name',
        ),
    ]
