# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandelbrot', '0020_auto_20160131_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
    ]
