# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandelbrot', '0021_badge_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='roles',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='part_time',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmember',
            name='roles',
            field=models.ManyToManyField(to='mandelbrot.Role'),
        ),
    ]
