# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandelbrot', '0024_auto_20160131_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetail',
            name='public',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='public',
        ),
    ]
