# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandelbrot', '0026_auto_20160204_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
