# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandelbrot', '0027_expert_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('note', models.CharField(blank=True, max_length=128)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('presentable', models.BooleanField()),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_names', to='mandelbrot.Expert')),
            ],
        ),
    ]
