# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandelbrot', '0028_othername'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
