# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 23:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandelbrot', '0029_auto_20160204_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='start_date',
            field=models.DateField(default=datetime.date(2016, 2, 4)),
            preserve_default=False,
        ),
    ]
